name: CI and CD
on: 
  push:
    branches:
      master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm i

      - name: Generate
        run: npm run generate

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: .output/public
        env:
          GITHUB_TOKEN: ${{ secrets.CI_CD_TOKEN }}
